import mysql.connector as sqltor
import tkinter

root=tkinter.Tk()
root.title("DVDMS")
root.geometry('1920x1080')

mycon=sqltor.connect(host="localhost",user="root",passwd="Chaitanya@17",database="dvdms")

if mycon.is_connected():
    print("\n")
    print("Welcome to DVDMS :)")
    c1=mycon.cursor()
    while True:      
        def home():
            
            
            def user():                
                lhome.destroy()
                buser.destroy() 
                bpublisher.destroy() 
                bgames.destroy()
                blog.destroy()
                bprogress.destroy()
                bul.destroy()
                bquit.destroy()
                c1.execute("select * from user")
                data=c1.fetchall()
                userstr=""
                for line in data:
                    str1=str(line)
                    str2=str1.strip()
                    userstr=userstr+str2+"\n"
                luser=tkinter.Label(root,text=userstr,font=("Calibri",20))
                luser.pack(anchor="nw")                 
                def backhomeuser():
                    buseradd.destroy()
                    buserupdate.destroy()
                    buserdelete.destroy()
                    buserback1.destroy()
                    luser.destroy()
                    home()
                def useradd():
                    def userappend():
                        def appenddone():
                            luserid.destroy()
                            euserid.destroy()
                            lusername.destroy()
                            eusername.destroy()
                            luserdob.destroy()
                            euserdob.destroy()
                            luseradd.destroy()
                            euseradd.destroy()
                            luserstd.destroy()
                            euserstd.destroy()
                            luserreg.destroy()
                            euserreg.destroy()
                            luseracc.destroy()
                            euseracc.destroy()
                            luserdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            backuseradd.destroy()
                            buserexecute.destroy()
                            user()
                        def appendcount():
                            luserid.destroy()
                            euserid.destroy()
                            lusername.destroy()
                            eusername.destroy()
                            luserdob.destroy()
                            euserdob.destroy()
                            luseradd.destroy()
                            euseradd.destroy()
                            luserstd.destroy()
                            euserstd.destroy()
                            luserreg.destroy()
                            euserreg.destroy()
                            luseracc.destroy()
                            euseracc.destroy()
                            luserdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            buserexecute.destroy()
                            useradd()
                        cid=euserid.get()
                        name=eusername.get()
                        dob=euserdob.get()
                        add=euseradd.get()
                        std=euserstd.get()
                        reg=euserreg.get()
                        acc=euseracc.get()
                        
                        st1=("insert into user values({},'{}','{}','{}','{}','{}','{}')".format(cid,name,dob,add,std,reg,acc))
                        c1.execute(st1)
                        mycon.commit()
                        
                        luserdone=tkinter.Label(root,text="Added successfully")
                        luserdone.pack()
                        bappd=tkinter.Button(root,text="Done",command=appenddone)
                        bappd.pack()
                        bcoapp=tkinter.Button(root,text="add more",command=appendcount)
                        bcoapp.pack()
                    buseradd.destroy()
                    buserupdate.destroy()
                    buserdelete.destroy()
                    buserback1.destroy()
                    luser.destroy()
                    
                    luserid=tkinter.Label(root,text="Enter customer id below")
                    luserid.pack()
                    euserid=tkinter.Entry(root,borderwidth=5)
                    euserid.pack()
                      
                    lusername=tkinter.Label(root,text="Enter customer name")
                    lusername.pack()
                    eusername=tkinter.Entry(root,width=30,borderwidth=5)
                    eusername.pack()
                   
                    luserdob=tkinter.Label(root,text="Enter customer date of birth")
                    luserdob.pack()
                    euserdob=tkinter.Entry(root,borderwidth=5)
                    euserdob.pack()
                    
                    luseradd=tkinter.Label(root,text="Enter customer address")
                    luseradd.pack()
                    euseradd=tkinter.Entry(root,width=100,borderwidth=5)
                    euseradd.pack()
                    
                    luserstd=tkinter.Label(root,text="Enter starting date")
                    luserstd.pack()
                    euserstd=tkinter.Entry(root,borderwidth=5)
                    euserstd.pack()
                    
                    luserreg=tkinter.Label(root,text="Enter customer region")
                    luserreg.pack()
                    euserreg=tkinter.Entry(root,width=20,borderwidth=5)
                    euserreg.pack()
                    
                    luseracc=tkinter.Label(root,text="Enter customer account linked")
                    luseracc.pack()
                    euseracc=tkinter.Entry(root,width=40,borderwidth=5)
                    euseracc.pack()
                    
                    buserexecute=tkinter.Button(root,text="execute",command=userappend)
                    buserexecute.pack()
                    
                    def backuseradd():
                        luserid.destroy()
                        euserid.destroy()
                        lusername.destroy()
                        eusername.destroy()
                        luserdob.destroy()
                        euserdob.destroy()
                        luseradd.destroy()
                        euseradd.destroy()
                        luserstd.destroy()
                        euserstd.destroy()
                        luserreg.destroy()
                        euserreg.destroy()
                        luseracc.destroy()
                        euseracc.destroy()
                        buserexecute.destroy()
                        buserbackadd.destroy()
                        user()
                    buserbackadd=tkinter.Button(root,text="Back",font=("Calibri",20),command=backuseradd)
                    buserbackadd.pack()
                    
                def userupdate():                  
                    def userudt():
                        def updatedone():
                            buserbackupdate.destroy()
                            luserid.destroy()
                            euserid.destroy()
                            luseradd.destroy()
                            euseradd.destroy()
                            buserexecute.destroy()
                            luserdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            user()
                        def updatecont():
                            buserbackupdate.destroy()
                            luserid.destroy()
                            euserid.destroy()
                            luseradd.destroy()
                            euseradd.destroy()
                            buserexecute.destroy()
                            luserdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            userupdate()
                        
                        cid=euserid.get()
                        add=euseradd.get()
                        
                        st1="update user set Address='{}' where Customer_Id={}".format(add,cid)
                        c1.execute(st1)
                        mycon.commit()
                        
                        luserdone=tkinter.Label(root,text="Updated successfully")
                        luserdone.pack()
                        budtd=tkinter.Button(root,text="Done",command=updatedone)
                        budtd.pack()
                        bcoudt=tkinter.Button(root,text="UPDATE more",command=updatecont)
                        bcoudt.pack()
                        
                    buseradd.destroy()
                    buserupdate.destroy()
                    buserdelete.destroy()
                    buserback1.destroy()
                    luser.destroy()
                    
                    luserid=tkinter.Label(root,text="Enter customer id below")
                    luserid.pack()
                    euserid=tkinter.Entry(root,borderwidth=5)
                    euserid.pack()
                    luseradd=tkinter.Label(root,text="Enter new address")
                    luseradd.pack()
                    euseradd=tkinter.Entry(root,width=100,borderwidth=5)
                    euseradd.pack()
                    buserexecute=tkinter.Button(root,text="execute",command=userudt)
                    buserexecute.pack()
                    
                    def backuserupdate():
                        luserid.destroy()
                        euserid.destroy()
                        luseradd.destroy()
                        euseradd.destroy()
                        buserexecute.destroy()
                        buserbackupdate.destroy()
                        user()
                        
                    buserbackupdate=tkinter.Button(root,text="Back",font=("Calibri",20),command=backuserupdate)
                    buserbackupdate.pack()
                    
                def userdelete():
                    def userdlt():
                        def deletedone():
                            buserbackdlt.destroy()
                            luserid.destroy()
                            euserid.destroy()
                            buserexecute.destroy()
                            luserdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            user()
                        def deletecont():
                            buserbackdlt.destroy()
                            luserid.destroy()
                            euserid.destroy()
                            buserexecute.destroy()
                            luserdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            userdelete()
                        
                        cid=euserid.get()
                        st1="delete from user where Customer_Id={}".format(cid)
                        c1.execute(st1)
                        mycon.commit()
                        luserdone=tkinter.Label(root,text="Added successfully")
                        luserdone.pack()
                        bdltd=tkinter.Button(root,text="Done",command=deletedone)
                        bdltd.pack()
                        bcodlt=tkinter.Button(root,text="delete more",command=deletecont)
                        bcodlt.pack()
                        
                    buseradd.destroy()
                    buserupdate.destroy()
                    buserdelete.destroy()
                    buserback1.destroy()
                    luser.destroy()
                    luserid=tkinter.Label(root,text="Enter customer id below")
                    luserid.pack()
                    euserid=tkinter.Entry(root,borderwidth=5)
                    euserid.pack()
                    buserexecute=tkinter.Button(root,text="execute",command=userdlt)
                    buserexecute.pack()
                       
                    def backuserdlt():
                        luserid.destroy()
                        euserid.destroy()
                        buserexecute.destroy()
                        buserbackdlt.destroy()
                        user()
                        
                    buserbackdlt=tkinter.Button(root,text="Back",font=("Calibri",20),command=backuserdlt)
                    buserbackdlt.pack()
                    
                buseradd=tkinter.Button(root,text="ADD A USER",font=("Calibri",20), command=useradd)
                buseradd.pack(pady=20)
                buserupdate=tkinter.Button(root,text="UPDATE A USER",font=("Calibri",20), command=userupdate)
                buserupdate.pack(pady=20)
                buserdelete=tkinter.Button(root,text="DELETE A USER",font=("Calibri",20), command=userdelete)
                buserdelete.pack(pady=20)
                buserback1=tkinter.Button(root,text="<-Back",font=("Calibri",20), command=backhomeuser)
                buserback1.pack()
                

            def publisher():
                lhome.destroy()
                buser.destroy() 
                bpublisher.destroy() 
                bgames.destroy()
                blog.destroy()
                bprogress.destroy()
                bul.destroy()
                bquit.destroy()
                c1.execute("select * from publisher")
                data=c1.fetchall()
                publisherstr=""
                for line in data:
                    str1=str(line)
                    str2=str1.strip()
                    publisherstr=publisherstr+str2+"\n"
                lpublisher=tkinter.Label(root,text=publisherstr,font=("Calibri",20))
                lpublisher.pack(anchor="nw")
                def backhomepublisher():
                    bpublisheradd.destroy()
                    bpublisherupdate.destroy()
                    bpublisherdelete.destroy()
                    lpublisher.destroy()
                    bpublisherback1.destroy()
                    home()
                def publisheradd():
                    def publisherappend():                             
                        def appenddone():
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            lpublishername.destroy()
                            epublishername.destroy()
                            lpublishercomper.destroy()
                            epublishercomper.destroy()
                            lpublishernetwo.destroy()
                            epublishernetwo.destroy()
                            lpublisherinvest.destroy()
                            epublisherinvest.destroy()
                            lpublisherdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bpublisherexecute.destroy()
                            bpublisherbackadd.destroy()
                            publisher()
                        def appendcount():
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            lpublishername.destroy()
                            epublishername.destroy()
                            lpublishercomper.destroy()
                            epublishercomper.destroy()
                            lpublishernetwo.destroy()
                            epublishernetwo.destroy()
                            lpublisherinvest.destroy()
                            epublisherinvest.destroy()
                            lpublisherdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bpublisherexecute.destroy()
                            bpublisherbackadd.destroy()
                            publisheradd()
                        pid=epublisherid.get()
                        name=epublishername.get()
                        comper=epublishercomper.get()
                        netwo=epublishernetwo.get()
                        invest=epublisherinvest.get()
                        st1="insert into publisher values({},'{}',{},{},{})".format(pid,name,comper,netwo,invest)
                        c1.execute(st1)
                        mycon.commit()
                        lpublisherdone=tkinter.Label(root,text="Added successfully")
                        lpublisherdone.pack()
                        bappd=tkinter.Button(root,text="Done",command=appenddone)
                        bappd.pack()
                        bcoapp=tkinter.Button(root,text="add more",command=appendcount)
                        bcoapp.pack()
                    bpublisheradd.destroy()
                    bpublisherupdate.destroy()
                    bpublisherdelete.destroy()
                    bpublisherback1.destroy()
                    lpublisher.destroy()
                    lpublisherid=tkinter.Label(root,text="Enter publisher id below")
                    lpublisherid.pack()
                    epublisherid=tkinter.Entry(root,borderwidth=5)
                    epublisherid.pack()
                      
                    lpublishername=tkinter.Label(root,text="Enter publisher name")
                    lpublishername.pack()
                    epublishername=tkinter.Entry(root,width=30,borderwidth=5)
                    epublishername.pack()
                   
                    lpublishercomper=tkinter.Label(root,text="Enter commission per cent")
                    lpublishercomper.pack()
                    epublishercomper=tkinter.Entry(root,borderwidth=5)
                    epublishercomper.pack()
                    
                    lpublishernetwo=tkinter.Label(root,text="Enter net worth")
                    lpublishernetwo.pack()
                    epublishernetwo=tkinter.Entry(root,width=100,borderwidth=5)
                    epublishernetwo.pack()
                    
                    lpublisherinvest=tkinter.Label(root,text="Enter investment amount")
                    lpublisherinvest.pack()
                    epublisherinvest=tkinter.Entry(root,borderwidth=5)
                    epublisherinvest.pack()

                    bpublisherexecute=tkinter.Button(root,text="execute",command=publisherappend)
                    bpublisherexecute.pack()

                    def backpublisheradd():
                        lpublisherid.destroy()
                        epublisherid.destroy()
                        lpublishername.destroy()
                        epublishername.destroy()
                        lpublishercomper.destroy()
                        epublishercomper.destroy()
                        lpublishernetwo.destroy()
                        epublishernetwo.destroy()
                        lpublisherinvest.destroy()
                        epublisherinvest.destroy()
                        bpublisherexecute.destroy()
                        bpublisherbackadd.destroy()
                        publisher()
                    bpublisherbackadd=tkinter.Button(root,text="Back",font=("Calibri",20),command=backpublisheradd)
                    bpublisherbackadd.pack()
                def publisherupdate():
                    def publisherudt():
                        def updatedone():
                            bpublisherbackupdate.destroy()
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            lpublishernetwo.destroy()
                            epublishernetwo.destroy()
                            bpublisherexecute.destroy()
                            lpublisherdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            publisher()
                        def updatecont():
                            bpublisherbackupdate.destroy()
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            lpublishernetwo.destroy()
                            epublishernetwo.destroy()
                            bpublisherexecute.destroy()
                            lpublisherdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            publisherupdate()
                        pid=epublisherid.get()
                        netwo=epublishernetwo.get()
                        st1="update publisher set net_worth_bd={} where publisher_id={}".format(netwo,pid)
                        c1.execute(st1)
                        mycon.commit()
                        lpublisherdone=tkinter.Label(root,text="Updated successfully")
                        lpublisherdone.pack()
                        budtd=tkinter.Button(root,text="Done",command=updatedone)
                        budtd.pack()
                        bcoudt=tkinter.Button(root,text="UPDATE more",command=updatecont)
                        bcoudt.pack()
                    bpublisheradd.destroy()
                    bpublisherupdate.destroy()
                    bpublisherdelete.destroy()
                    bpublisherback1.destroy()
                    lpublisher.destroy()
                    lpublisherid=tkinter.Label(root,text="Enter publisher id below")
                    lpublisherid.pack()
                    epublisherid=tkinter.Entry(root,borderwidth=5)
                    epublisherid.pack()
                    lpublishernetwo=tkinter.Label(root,text="Enter net worth")
                    lpublishernetwo.pack()
                    epublishernetwo=tkinter.Entry(root,width=100,borderwidth=5)
                    epublishernetwo.pack()
                    bpublisherexecute=tkinter.Button(root,text="execute",command=publisherudt)
                    bpublisherexecute.pack()
                    def backpublisherupdate():
                        lpublisherid.destroy()
                        epublisherid.destroy()
                        lpublishernetwo.destroy()
                        epublishernetwo.destroy()
                        bpublisherexecute.destroy()
                        bpublisherbackupdate.destroy()
                        publisher()
                    bpublisherbackupdate=tkinter.Button(root,text="Back",font=("Calibri",20),command=backpublisherupdate)
                    bpublisherbackupdate.pack()
                def publisherdelete():
                    def publisherdlt():
                        def deletedone():
                            bpublisherbackdlt.destroy()
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            bpublisherexecute.destroy()
                            lpublisherdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            publisher()
                        def deletecont():
                            bpublisherbackdlt.destroy()
                            lpublisherid.destroy()
                            epublisherid.destroy()
                            bpublisherexecute.destroy()
                            lpublisherdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            publisherdelete()
                        pid=epublisherid.get()
                        st1="delete from publisher where publisher_id={}".format(pid)
                        c1.execute(st1)
                        mycon.commit()
                        lpublisherdone=tkinter.Label(root,text="Deleted successfully")
                        lpublisherdone.pack()
                        bdltd=tkinter.Button(root,text="Done",command=deletedone)
                        bdltd.pack()
                        bcodlt=tkinter.Button(root,text="delete more",command=deletecont)
                        bcodlt.pack()
                    bpublisheradd.destroy()
                    bpublisherupdate.destroy()
                    bpublisherdelete.destroy()
                    bpublisherback1.destroy()
                    lpublisher.destroy()
                    lpublisherid=tkinter.Label(root,text="Enter publisher id below")
                    lpublisherid.pack()
                    epublisherid=tkinter.Entry(root,borderwidth=5)
                    epublisherid.pack()
                    bpublisherexecute=tkinter.Button(root,text="execute",command=publisherdlt)
                    bpublisherexecute.pack()
                    def backpublisherdlt():
                        lpublisherid.destroy()
                        epublisherid.destroy()
                        bpublisherexecute.destroy()
                        bpublisherbackdlt.destroy()
                        publisher()
                    bpublisherbackdlt=tkinter.Button(root,text="Back",font=("Calibri",20),command=backpublisherdlt)
                    bpublisherbackdlt.pack()
                bpublisheradd=tkinter.Button(root,text="ADD A PUBLISHER",font=("Calibri",20), command=publisheradd)
                bpublisheradd.pack(pady=20)
                bpublisherupdate=tkinter.Button(root,text="UPDATE A PUBLISHER",font=("Calibri",20), command=publisherupdate)
                bpublisherupdate.pack(pady=20)
                bpublisherdelete=tkinter.Button(root,text="DELETE A PUBLISHER",font=("Calibri",20), command=publisherdelete)
                bpublisherdelete.pack(pady=20)
                bpublisherback1=tkinter.Button(root,text="<-Back",font=("Calibri",20), command=backhomepublisher)
                bpublisherback1.pack()
    
            def games():
                lhome.destroy()
                buser.destroy() 
                bpublisher.destroy() 
                bgames.destroy()
                blog.destroy()
                bprogress.destroy()
                bul.destroy()
                bquit.destroy()
                c1.execute("select * from games")
                data=c1.fetchall()
                gamesstr=""
                for line in data:
                    str1=str(line)
                    str2=str1.strip()
                    gamesstr=gamesstr+str2+"\n"
                lgames=tkinter.Label(root,text=gamesstr,font=("Calibri",20))
                lgames.pack(anchor="nw")
                def backhomegames():
                    bgamesadd.destroy()
                    bgamesupdate.destroy()
                    bgamesdelete.destroy()
                    lgames.destroy()
                    bgamesback1.destroy()
                    home()
                def gamesadd():
                    def gamesappend():
                        def appenddone():
                            lgamesid.destroy()
                            egamesid.destroy()
                            lgamesgenre.destroy()
                            egamesgenre.destroy()
                            lgamesname.destroy()
                            egamesname.destroy()
                            lgamespublisher.destroy()
                            egamespublisher.destroy()
                            lgamesmrp.destroy()
                            egamesmrp.destroy()
                            lgamesdiscprice.destroy()
                            egamesdiscprice.destroy()
                            lgamesdiscper.destroy()
                            egamesdiscper.destroy()
                            lgamessell.destroy()
                            egamessell.destroy()
                            lgamesdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bgamesexecute.destroy()
                            bgamesbackadd.destroy()
                            games()
                        def appendcount():
                            lgamesid.destroy()
                            egamesid.destroy()
                            lgamesgenre.destroy()
                            egamesgenre.destroy()
                            lgamesname.destroy()
                            egamesname.destroy()
                            lgamespublisher.destroy()
                            egamespublisher.destroy()
                            lgamesmrp.destroy()
                            egamesmrp.destroy()
                            lgamesdiscprice.destroy()
                            egamesdiscprice.destroy()
                            lgamesdiscper.destroy()
                            egamesdiscper.destroy()
                            lgamesdone.destroy()
                            lgamessell.destroy()
                            egamessell.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bgamesexecute.destroy()
                            bgamesbackadd.destroy()
                            gamesadd()
                        gid=egamesid.get()
                        genre=egamesgenre.get()
                        name=egamesname.get()
                        publisher=egamespublisher.get()
                        mrp=egamesmrp.get()
                        discprice=egamesdiscprice.get()
                        discper=egamesdiscper.get()
                        sell=egamessell.get()
                        st1="insert into Games values({},'{}','{}','{}',{},{},{},{})".format(gid,genre,name,publisher,mrp,discprice,discper,sell) 
                        c1.execute(st1)
                        mycon.commit()
                        lgamesdone=tkinter.Label(root,text="Added successfully")
                        lgamesdone.pack()
                        bappd=tkinter.Button(root,text="Done",command=appenddone)
                        bappd.pack()
                        bcoapp=tkinter.Button(root,text="add more",command=appendcount)
                        bcoapp.pack()
                    bgamesadd.destroy()
                    bgamesupdate.destroy()
                    bgamesdelete.destroy()
                    bgamesback1.destroy()
                    lgames.destroy()
                    lgamesid=tkinter.Label(root,text="Enter game id below")
                    lgamesid.pack()
                    egamesid=tkinter.Entry(root,borderwidth=5)
                    egamesid.pack()
                      
                    lgamesgenre=tkinter.Label(root,text="Enter genre name")
                    lgamesgenre.pack()
                    egamesgenre=tkinter.Entry(root,width=30,borderwidth=5)
                    egamesgenre.pack()
                   
                    lgamesname=tkinter.Label(root,text="Enter game name")
                    lgamesname.pack()
                    egamesname=tkinter.Entry(root,borderwidth=5)
                    egamesname.pack()
                    
                    lgamespublisher=tkinter.Label(root,text="Enter publisher name")
                    lgamespublisher.pack()
                    egamespublisher=tkinter.Entry(root,width=100,borderwidth=5)
                    egamespublisher.pack()
                    
                    lgamesmrp=tkinter.Label(root,text="Enter mrp")
                    lgamesmrp.pack()
                    egamesmrp=tkinter.Entry(root,borderwidth=5)
                    egamesmrp.pack()
                    
                    lgamesdiscprice=tkinter.Label(root,text="Enter disc price")
                    lgamesdiscprice.pack()
                    egamesdiscprice=tkinter.Entry(root,width=20,borderwidth=5)
                    egamesdiscprice.pack()
                    
                    lgamesdiscper=tkinter.Label(root,text="Enter disc percent")
                    lgamesdiscper.pack()
                    egamesdiscper=tkinter.Entry(root,width=40,borderwidth=5)
                    egamesdiscper.pack()

                    lgamessell=tkinter.Label(root,text="Enter copies sold")
                    lgamessell.pack()
                    egamessell=tkinter.Entry(root,width=40,borderwidth=5)
                    egamessell.pack()
                    
                    bgamesexecute=tkinter.Button(root,text="execute",command=gamesappend)
                    bgamesexecute.pack()
                    def backgamesadd():
                        lgamesid.destroy()
                        egamesid.destroy()
                        lgamesgenre.destroy()
                        egamesgenre.destroy()
                        lgamesname.destroy()
                        egamesname.destroy()
                        lgamesdiscprice.destroy()
                        egamesdiscprice.destroy()
                        lgamesdiscper.destroy()
                        egamesdiscper.destroy()
                        lgamesmrp.destroy()
                        egamesmrp.destroy()
                        lgamespublisher.destroy()
                        egamespublisher.destroy()
                        lgamessell.destroy()
                        egamessell.destroy()
                        bgamesexecute.destroy()
                        bgamesbackadd.destroy()
                        games()
                    bgamesbackadd=tkinter.Button(root,text="Back",font=("Calibri",20),command=backgamesadd)
                    bgamesbackadd.pack()
                def gamesupdate():
                     
                    def gamesudt():
                        def updatedone():
                            bgamesbackupdate.destroy()
                            lgamesid.destroy()
                            egamesid.destroy()
                            lgamesdiscprice.destroy()
                            egamesdiscprice.destroy()
                            bgamesexecute.destroy()
                            lgamesdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            games()
                        def updatecont():
                            bgamesbackupdate.destroy()
                            lgamesid.destroy()
                            egamesid.destroy()
                            lgamesdiscprice.destroy()
                            egamesdiscprice.destroy()
                            bgamesexecute.destroy()
                            lgamesdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            gamesupdate()
                        
                        gid=int(egamesid.get())
                        newprice=int(egamesdiscprice.get())
                        for i in data:             
                             if i[0]==gid:
                                 st1= "update games set Disc_Price={} where Game_Id={}".format(newprice,gid)
                                 mrp=i[4]
                                 dp=((mrp-newprice)/mrp)*100
                                 st2="update games set Disc_Per={} where Game_Id={}".format(dp,gid)
                                 c1.execute(st1)
                                 c1.execute(st2)
                                 mycon.commit()
                        lgamesdone=tkinter.Label(root,text="Updated successfully")
                        lgamesdone.pack()
                        budtd=tkinter.Button(root,text="Done",command=updatedone)
                        budtd.pack()
                        bcoudt=tkinter.Button(root,text="UPDATE more",command=updatecont)
                        bcoudt.pack()
                        
                    bgamesadd.destroy()
                    bgamesupdate.destroy()
                    bgamesdelete.destroy()
                    bgamesback1.destroy()
                    lgames.destroy()
                    lgamesid=tkinter.Label(root,text="Enter game id below")
                    lgamesid.pack()
                    egamesid=tkinter.Entry(root,borderwidth=5)
                    egamesid.pack()
                    lgamesdiscprice=tkinter.Label(root,text="Enter new price")
                    lgamesdiscprice.pack()
                    egamesdiscprice=tkinter.Entry(root,width=100,borderwidth=5)
                    egamesdiscprice.pack()
                    bgamesexecute=tkinter.Button(root,text="execute",command=gamesudt)
                    bgamesexecute.pack()
                    
                    
                  
                    def backgamesupdate():
                        lgamesid.destroy()
                        egamesid.destroy()
                        lgamesdiscprice.destroy()
                        egamesdiscprice.destroy()
                        bgamesexecute.destroy()
                        bgamesbackupdate.destroy()
                        games()
                    bgamesbackupdate=tkinter.Button(root,text="Back",font=("Calibri",20),command=backgamesupdate)
                    bgamesbackupdate.pack()
                    
                def gamesdelete():
                    def gamesdlt():
                        def deletedone():
                            bgamesbackdlt.destroy()
                            lgamesid.destroy()
                            egamesid.destroy()
                            bgamesexecute.destroy()
                            lgamesdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            games()
                        def deletecont():
                            bgamesbackdlt.destroy()
                            lgamesid.destroy()
                            egamesid.destroy()
                            bgamesexecute.destroy()
                            lgamesdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            gamesdelete()
                        
                        gid=egamesid.get()
                        st1="delete from Games where Game_Id={}".format(gid)
                        c1.execute(st1)
                        mycon.commit()
                        lgamesdone=tkinter.Label(root,text="Added successfully")
                        lgamesdone.pack()
                        bdltd=tkinter.Button(root,text="Done",command=deletedone)
                        bdltd.pack()
                        bcodlt=tkinter.Button(root,text="delete more",command=deletecont)
                        bcodlt.pack()
                        
                    bgamesadd.destroy()
                    bgamesupdate.destroy()
                    bgamesdelete.destroy()
                    bgamesback1.destroy()
                    lgames.destroy()
                    lgamesid=tkinter.Label(root,text="Enter game id below")
                    lgamesid.pack()
                    egamesid=tkinter.Entry(root,borderwidth=5)
                    egamesid.pack()
                    bgamesexecute=tkinter.Button(root,text="execute",command=gamesdlt)
                    bgamesexecute.pack()
                    
                    
                  
                    def backgamesdlt():
                        lgamesid.destroy()
                        egamesid.destroy()
                        bgamesexecute.destroy()
                        bgamesbackdlt.destroy()
                        games()
                    bgamesbackdlt=tkinter.Button(root,text="Back",font=("Calibri",20),command=backgamesdlt)
                    bgamesbackdlt.pack()
                    
                bgamesadd=tkinter.Button(root,text="ADD GAMES",font=("Calibri",20), command=gamesadd)
                bgamesadd.pack(pady=20)
                bgamesupdate=tkinter.Button(root,text="UPDATE A GAME",font=("Calibri",20), command=gamesupdate)
                bgamesupdate.pack(pady=20)
                bgamesdelete=tkinter.Button(root,text="DELETE GAMES",font=("Calibri",20), command=gamesdelete)
                bgamesdelete.pack(pady=20)
                bgamesback1=tkinter.Button(root,text="<-Back",font=("Calibri",20), command=backhomegames)
                bgamesback1.pack()                    
        
            def log():
                lhome.destroy()
                buser.destroy() 
                bpublisher.destroy() 
                bgames.destroy()
                blog.destroy()
                bprogress.destroy()
                bul.destroy()
                bquit.destroy()
                c1.execute("select * from log")
                data=c1.fetchall()
                logstr=""
                for line in data:
                    str1=str(line)
                    str2=str1.strip()
                    logstr=logstr+str2+"\n"
                llog=tkinter.Label(root,text=logstr,font=("Calibri",20))
                llog.pack(anchor="nw")
                def backhomelog():
                    blogadd.destroy()
                    blogback1.destroy()
                    llog.destroy()
                    home()
                def logadd():
                    def logappend():
                        def appenddone():
                            llogsrno.destroy()
                            elogsrno.destroy()
                            llogcid.destroy()
                            elogcid.destroy()
                            lloggid.destroy()
                            eloggid.destroy()
                            llogname.destroy()
                            elogname.destroy()
                            llogdop.destroy()
                            elogdop.destroy()
                            llogmrp.destroy()
                            elogmrp.destroy()
                            llogov.destroy()
                            elogov.destroy()
                            llogdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            blogexecute.destroy()
                            blogbackadd.destroy()
                            log()
                        def appendcount():
                            llogsrno.destroy()
                            elogsrno.destroy()
                            llogcid.destroy()
                            elogcid.destroy()
                            lloggid.destroy()
                            eloggid.destroy()
                            llogname.destroy()
                            elogname.destroy()
                            llogdop.destroy()
                            elogdop.destroy()
                            llogmrp.destroy()
                            elogmrp.destroy()
                            llogov.destroy()
                            elogov.destroy()
                            llogdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            blogexecute.destroy()
                            blogbackadd.destroy()
                            logadd()
                        srno=elogsrno.get()
                        cid=elogcid.get()
                        gid=eloggid.get()
                        name=elogname.get()
                        dop=elogdop.get()
                        mrp=elogmrp.get()
                        ov=elogov.get()
                        st1="insert into log values({},{},{},'{}','{}',{},{})".format(srno,cid,gid,name,dop,mrp,ov)
                        c1.execute(st1)
                        if cid == "400001":
                            st2="insert into ramesh values({},'{}','{}')".format(gid,name,dop)
                            c1.execute(st2)
                        elif cid=="400002":
                            st2="insert into kamlesh values({},'{}','{}')".format(gid,name,dop)
                            c1.execute(st2)         
                        mycon.commit()
                        llogdone=tkinter.Label(root,text="Added successfully")
                        llogdone.pack()
                        bappd=tkinter.Button(root,text="Done",command=appenddone)
                        bappd.pack()
                        bcoapp=tkinter.Button(root,text="add more",command=appendcount)
                        bcoapp.pack()
                    blogadd.destroy()
                    blogback1.destroy()
                    llog.destroy()
                    llogsrno=tkinter.Label(root,text="Enter srno")
                    llogsrno.pack()
                    elogsrno=tkinter.Entry(root,borderwidth=5)
                    elogsrno.pack()
                      
                    llogcid=tkinter.Label(root,text="Enter customer id")
                    llogcid.pack()
                    elogcid=tkinter.Entry(root,width=30,borderwidth=5)
                    elogcid.pack()
                   
                    lloggid=tkinter.Label(root,text="Enter game id")
                    lloggid.pack()
                    eloggid=tkinter.Entry(root,borderwidth=5)
                    eloggid.pack()
                    
                    llogname=tkinter.Label(root,text="Enter game name")
                    llogname.pack()
                    elogname=tkinter.Entry(root,width=100,borderwidth=5)
                    elogname.pack()
                    
                    llogdop=tkinter.Label(root,text="Enter purchase date")
                    llogdop.pack()
                    elogdop=tkinter.Entry(root,borderwidth=5)
                    elogdop.pack()
                    
                    llogmrp=tkinter.Label(root,text="Enter mrp")
                    llogmrp.pack()
                    elogmrp=tkinter.Entry(root,width=20,borderwidth=5)
                    elogmrp.pack()
                    
                    llogov=tkinter.Label(root,text="Enter order value")
                    llogov.pack()
                    elogov=tkinter.Entry(root,width=40,borderwidth=5)
                    elogov.pack()
                    
                    blogexecute=tkinter.Button(root,text="execute",command=logappend)
                    blogexecute.pack()
                    def backlogadd():
                        llogsrno.destroy()
                        elogsrno.destroy()
                        llogcid.destroy()
                        elogcid.destroy()
                        lloggid.destroy()
                        eloggid.destroy()
                        llogname.destroy()
                        elogname.destroy()
                        llogdop.destroy()
                        elogdop.destroy()
                        llogmrp.destroy()
                        elogmrp.destroy()
                        llogov.destroy()
                        elogov.destroy()
                        blogexecute.destroy()
                        blogbackadd.destroy()
                        log()
                    blogbackadd=tkinter.Button(root,text="Back",font=("Calibri",20),command=backlogadd)
                    blogbackadd.pack()
                blogadd=tkinter.Button(root,text="ADD A LOG",font=("Calibri",20), command=logadd)
                blogadd.pack(pady=20)
                blogback1=tkinter.Button(root,text="Back",font=("Calibri",20), command=backhomelog)
                blogback1.pack()

            def progress():
                lhome.destroy()
                buser.destroy() 
                bpublisher.destroy() 
                bgames.destroy()
                blog.destroy()
                bprogress.destroy()
                bul.destroy()
                bquit.destroy()
                c1.execute("select * from progress")
                data=c1.fetchall()
                progressstr=""
                for line in data:
                    str1=str(line)
                    str2=str1.strip()
                    progressstr=progressstr+str2+"\n"
                lprogress=tkinter.Label(root,text=progressstr,font=("Calibri",20))
                lprogress.pack(anchor="nw")
                def backhomeprogress():
                    bprogressadd.destroy()
                    bprogressupdate.destroy()
                    bprogressdelete.destroy()
                    lprogress.destroy()
                    bprogressback1.destroy()
                    home()

                def progressadd():
                    def progressappend():
                        def appenddone():
                            lprogresssrno.destroy()
                            eprogresssrno.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            lprogressname.destroy()
                            eprogressname.destroy()
                            lprogressprofit.destroy()
                            eprogressprofit.destroy()
                            lprogressdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bprogressexecute.destroy()
                            bprogressbackadd.destroy()
                            progress()
                        def appendcount():
                            lprogresssrno.destroy()
                            eprogresssrno.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            lprogressname.destroy()
                            eprogressname.destroy()
                            lprogressprofit.destroy()
                            eprogressprofit.destroy()
                            lprogressdone.destroy()
                            bappd.destroy()
                            bcoapp.destroy()
                            bprogressexecute.destroy()
                            bprogressbackadd.destroy()
                            progressadd()
                        srno=eprogresssrno.get()
                        pid=eprogresspid.get()
                        name=eprogressname.get()
                        profit=eprogressprofit.get()
                        st1="insert into progress values({},{},'{}',{})".format(srno,pid,name,profit)
                        c1.execute(st1)
                        mycon.commit()
                        lprogressdone=tkinter.Label(root,text="Added successfully")
                        lprogressdone.pack()
                        bappd=tkinter.Button(root,text="Done",command=appenddone)
                        bappd.pack()
                        bcoapp=tkinter.Button(root,text="add more",command=appendcount)
                        bcoapp.pack()
                    bprogressadd.destroy()
                    bprogressupdate.destroy()
                    bprogressdelete.destroy()
                    bprogressback1.destroy()
                    lprogress.destroy()
                    
                      
                    lprogresssrno=tkinter.Label(root,text="Enter srno")
                    lprogresssrno.pack()
                    eprogresssrno=tkinter.Entry(root,width=30,borderwidth=5)
                    eprogresssrno.pack()
                   
                    lprogresspid=tkinter.Label(root,text="Enter publisher id")
                    lprogresspid.pack()
                    eprogresspid=tkinter.Entry(root,borderwidth=5)
                    eprogresspid.pack()
                    
                    lprogressname=tkinter.Label(root,text="Enter name")
                    lprogressname.pack()
                    eprogressname=tkinter.Entry(root,width=100,borderwidth=5)
                    eprogressname.pack()
                    
                    lprogressprofit=tkinter.Label(root,text="Enter rofit in millions")
                    lprogressprofit.pack()
                    eprogressprofit=tkinter.Entry(root,borderwidth=5)
                    eprogressprofit.pack()
                    
                    
                    bprogressexecute=tkinter.Button(root,text="execute",command=progressappend)
                    bprogressexecute.pack()
                    def backprogressadd():
                        lprogresssrno.destroy()
                        eprogresssrno.destroy()
                        lprogresspid.destroy()
                        eprogresspid.destroy()
                        lprogressname.destroy()
                        eprogressname.destroy()
                        lprogressprofit.destroy()
                        eprogressprofit.destroy()
                        bprogressexecute.destroy()
                        bprogressbackadd.destroy()
                        progress()
                    bprogressbackadd=tkinter.Button(root,text="Back",font=("Calibri",20),command=backprogressadd)
                    bprogressbackadd.pack()
                
                def progressupdate():
                     
                    def progressudt():
                        def updatedone():
                            bprogressbackupdate.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            lprogressprofit.destroy()
                            eprogressprofit.destroy()
                            bprogressexecute.destroy()
                            lprogressdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            progress()
                        def updatecont():
                            bprogressbackupdate.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            lprogressprofit.destroy()
                            eprogressprofit.destroy()
                            bprogressexecute.destroy()
                            lprogressdone.destroy()
                            budtd.destroy()
                            bcoudt.destroy()
                            progressupdate()
                        
                        pid=eprogresspid.get()
                        profit=eprogressprofit.get()
                        st1="update progress set Profit_In_Millions={} where Publisher_Id={}".format(profit,pid)
                        c1.execute(st1)
                        mycon.commit()
                        lprogressdone=tkinter.Label(root,text="Updated successfully")
                        lprogressdone.pack()
                        budtd=tkinter.Button(root,text="Done",command=updatedone)
                        budtd.pack()
                        bcoudt=tkinter.Button(root,text="UPDATE more",command=updatecont)
                        bcoudt.pack()
                        
                    bprogressadd.destroy()
                    bprogressupdate.destroy()
                    bprogressdelete.destroy()
                    bprogressback1.destroy()
                    lprogress.destroy()
                    lprogresspid=tkinter.Label(root,text="Enter publisher id below")
                    lprogresspid.pack()
                    eprogresspid=tkinter.Entry(root,borderwidth=5)
                    eprogresspid.pack()
                    lprogressprofit=tkinter.Label(root,text="Enter new profit")
                    lprogressprofit.pack()
                    eprogressprofit=tkinter.Entry(root,width=100,borderwidth=5)
                    eprogressprofit.pack()
                    bprogressexecute=tkinter.Button(root,text="execute",command=progressudt)
                    bprogressexecute.pack()
                    
                    
                  
                    def backprogressupdate():
                        lprogresspid.destroy()
                        eprogresspid.destroy()
                        lprogressprofit.destroy()
                        eprogressprofit.destroy()
                        bprogressexecute.destroy()
                        bprogressbackupdate.destroy()
                        progress()
                    bprogressbackupdate=tkinter.Button(root,text="Back",font=("Calibri",20),command=backprogressupdate)
                    bprogressbackupdate.pack()
                    
                def progressdelete():
                    def progressdlt():
                        def deletedone():
                            bprogressbackdlt.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            bprogressexecute.destroy()
                            lprogressdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            progress()
                        def deletecont():
                            bprogressbackdlt.destroy()
                            lprogresspid.destroy()
                            eprogresspid.destroy()
                            bprogressexecute.destroy()
                            lprogressdone.destroy()
                            bdltd.destroy()
                            bcodlt.destroy()
                            progressdelete()
                        
                        pid=eprogresspid.get()
                        st1="delete from progress where Publisher_Id={}".format(pid)
                        c1.execute(st1)
                        mycon.commit()
                        lprogressdone=tkinter.Label(root,text="Added successfully")
                        lprogressdone.pack()
                        bdltd=tkinter.Button(root,text="Done",command=deletedone)
                        bdltd.pack()
                        bcodlt=tkinter.Button(root,text="delete more",command=deletecont)
                        bcodlt.pack()
                        
                    bprogressadd.destroy()
                    bprogressupdate.destroy()
                    bprogressdelete.destroy()
                    bprogressback1.destroy()
                    lprogress.destroy()
                    lprogresspid=tkinter.Label(root,text="Enter publisher id below")
                    lprogresspid.pack()
                    eprogresspid=tkinter.Entry(root,borderwidth=5)
                    eprogresspid.pack()
                    bprogressexecute=tkinter.Button(root,text="execute",command=progressdlt)
                    bprogressexecute.pack()
                    
                    
                  
                    def backprogressdlt():
                        lprogresspid.destroy()
                        eprogresspid.destroy()
                        bprogressexecute.destroy()
                        bprogressbackdlt.destroy()
                        progress()
                    bprogressbackdlt=tkinter.Button(root,text="Back",font=("Calibri",20),command=backprogressdlt)
                    bprogressbackdlt.pack()
                    
                bprogressadd=tkinter.Button(root,text="ADD A PROGRESS",font=("Calibri",20), command=progressadd)
                bprogressadd.pack(pady=20)
                bprogressupdate=tkinter.Button(root,text="UPDATE A PROGRESS",font=("Calibri",20), command=progressupdate)
                bprogressupdate.pack(pady=20)
                bprogressdelete=tkinter.Button(root,text="DELETE A PROGRESS",font=("Calibri",20), command=progressdelete)
                bprogressdelete.pack(pady=20)
                bprogressback1=tkinter.Button(root,text="<-Back",font=("Calibri",20), command=backhomeprogress)
                bprogressback1.pack()                     


            def userlib():
                    lhome.destroy()
                    buser.destroy() 
                    bpublisher.destroy() 
                    bgames.destroy()
                    blog.destroy()
                    bprogress.destroy()
                    bul.destroy()
                    bquit.destroy()

                    def ramesh():
                        bulback.destroy()
                        bramesh.destroy()
                        bkamlesh.destroy()
                        bquit.destroy()
                        c1.execute("select * from ramesh")
                        data=c1.fetchall()
                        rameshstr=""
                        for line in data:
                            str1=str(line)
                            str2=str1.strip()
                            rameshstr=rameshstr+str2+"\n"
                        lramesh=tkinter.Label(root,text=rameshstr,font=("Calibri",20))
                        lramesh.pack(anchor="n")
                        def backulramesh():
                            lramesh.destroy()
                            brameshback1.destroy()
                            userlib()
                        brameshback1=tkinter.Button(root,text="Back",font=("Calibri",20), command=backulramesh)
                        brameshback1.pack()
            
                    def kamlesh():
                        bulback.destroy()
                        bramesh.destroy()
                        bkamlesh.destroy()
                        bquit.destroy()
                        c1.execute("select * from kamlesh")
                        data=c1.fetchall()
                        kamleshstr=""
                        for line in data:
                            str1=str(line)
                            str2=str1.strip()
                            kamleshstr=kamleshstr+str2+"\n"
                        lkamlesh=tkinter.Label(root,text=kamleshstr,font=("Calibri",20))
                        lkamlesh.pack(anchor="n")
                        def backulkamlesh():
                            lkamlesh.destroy()
                            bkamleshback1.destroy()
                            userlib()
                        bkamleshback1=tkinter.Button(root,text="Back",font=("Calibri",20), command=backulkamlesh)
                        bkamleshback1.pack()
                    def ulback():
                        bramesh.destroy()
                        bkamlesh.destroy()
                        bulback.destroy()
                        home()        
                        
                    bramesh=tkinter.Button(root,text="Ramesh",font=("Calibri",20) , command=ramesh)
                    bramesh.pack()
                    bkamlesh=tkinter.Button(root,text="Kamlesh",font=("Calibri",20) , command=kamlesh)
                    bkamlesh.pack()
                    bulback=tkinter.Button(root,text="Back",font=("Calibri",20) , command=ulback)
                    bulback.pack()

            lhome=tkinter.Label(root,text="Welcome to DVDMS :)",font=("Calibri", 25))
            lhome.pack()
            buser=tkinter.Button(root,text="USER DETAILS",font=("Calibri",20), command=user)
            buser.pack()
    
            bpublisher=tkinter.Button(root,text="PUBLISHER DETAILS",font=("Calibri",20), command=publisher)
            bpublisher.pack()
    
            bgames=tkinter.Button(root,text="GAMES DETAILS",font=("Calibri",20), command=games)
            bgames.pack()
    
            blog=tkinter.Button(root,text="LOG DETAILS",font=("Calibri",20), command=log)
            blog.pack()
    
            bprogress=tkinter.Button(root,text="PROGRESS DETAILS",font=("Calibri",20), command=progress)
            bprogress.pack()
    
            bul=tkinter.Button(root,text="Users' Library", font=("Calibri",20) , command=userlib)
            bul.pack()

            bquit=tkinter.Button(root,text="QUIT",font=("Calibri",20),command=root.destroy)
            bquit.pack()

        home()
        root.mainloop()
        exit()
else:
    lerror=tkinter.Label(root,text="unable to connect to DVDMS :(")
    lerror.pack()
